export let ExhibitionSite = [
  { id: '1',
    name: 'Expo 1',
    // tslint:disable-next-line:max-line-length
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin et justo et arcu consequat condimentum. Suspendisse et malesuada ipsum. Nullam tristique finibus nibh sit amet maximus. Mauris facilisis odio metus, nec condimentum augue fermentum quis. Nullam commodo urna at nisi elementum, id pulvinar elit fringilla. Mauris ac consequat lorem. Nam in congue velit. Fusce vel interdum nisi. Quisque eu gravida eros, porta vulputate ipsum. Nunc tristique vehicula lacus, ut auctor justo mattis imperdiet.',
    exhibitionDate: '14-02-2022',
  },
  { id: '2',
    name: 'Expo2',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin et justo et arcu consequat condimentum. Suspendisse et malesuada ipsum. Nullam tristique finibus nibh sit amet maximus. Mauris facilisis odio metus, nec condimentum augue fermentum quis. Nullam commodo urna at nisi elementum, id pulvinar elit fringilla. Mauris ac consequat lorem. Nam in congue velit. Fusce vel interdum nisi. Quisque eu gravida eros, porta vulputate ipsum. Nunc tristique vehicula lacus, ut auctor justo mattis imperdiet.',
    exhibitionDate: '04-03-2022',
  },
  { id: '1',
    name: 'Expo3',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin et justo et arcu consequat condimentum. Suspendisse et malesuada ipsum. Nullam tristique finibus nibh sit amet maximus. Mauris facilisis odio metus, nec condimentum augue fermentum quis. Nullam commodo urna at nisi elementum, id pulvinar elit fringilla. Mauris ac consequat lorem. Nam in congue velit. Fusce vel interdum nisi. Quisque eu gravida eros, porta vulputate ipsum. Nunc tristique vehicula lacus, ut auctor justo mattis imperdiet.',
    exhibitionDate: '10-02-2022',
  },
  { id: '1',
    name: 'Expo 4',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin et justo et arcu consequat condimentum. Suspendisse et malesuada ipsum. Nullam tristique finibus nibh sit amet maximus. Mauris facilisis odio metus, nec condimentum augue fermentum quis. Nullam commodo urna at nisi elementum, id pulvinar elit fringilla. Mauris ac consequat lorem. Nam in congue velit. Fusce vel interdum nisi. Quisque eu gravida eros, porta vulputate ipsum. Nunc tristique vehicula lacus, ut auctor justo mattis imperdiet.',
    exhibitionDate: '16-09-2022',
  },
];
